# Generated by Django 3.2 on 2021-04-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0005_auto_20210420_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
    ]
