# Generated by Django 3.2 on 2021-04-20 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0006_remove_recipe_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='CookingApp.recipe'),
            preserve_default=False,
        ),
    ]
