# Generated by Django 3.2 on 2021-04-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0009_auto_20210420_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CookingApp.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creator_id',
            field=models.CharField(max_length=10),
        ),
    ]
