# Generated by Django 3.2 on 2021-04-20 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CookingApp', '0010_auto_20210420_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creator_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
